//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalCar.Service.Workflow.MyVehicleService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehicleDTO", Namespace="http://schemas.datacontract.org/2004/07/RentalCar.Core.Models")]
    [System.SerializableAttribute()]
    public partial class VehicleDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CurrentMileageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberOfBedsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberPlateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal RentalChargeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RentalCar.Service.Workflow.MyVehicleService.RoadTypes RoadTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ToiletField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Under21Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VehicleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RentalCar.Service.Workflow.MyVehicleService.VehicleTypes VehicleTypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double CurrentMileage {
            get {
                return this.CurrentMileageField;
            }
            set {
                if ((this.CurrentMileageField.Equals(value) != true)) {
                    this.CurrentMileageField = value;
                    this.RaisePropertyChanged("CurrentMileage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfBeds {
            get {
                return this.NumberOfBedsField;
            }
            set {
                if ((this.NumberOfBedsField.Equals(value) != true)) {
                    this.NumberOfBedsField = value;
                    this.RaisePropertyChanged("NumberOfBeds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumberPlate {
            get {
                return this.NumberPlateField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberPlateField, value) != true)) {
                    this.NumberPlateField = value;
                    this.RaisePropertyChanged("NumberPlate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal RentalCharge {
            get {
                return this.RentalChargeField;
            }
            set {
                if ((this.RentalChargeField.Equals(value) != true)) {
                    this.RentalChargeField = value;
                    this.RaisePropertyChanged("RentalCharge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RentalCar.Service.Workflow.MyVehicleService.RoadTypes RoadType {
            get {
                return this.RoadTypeField;
            }
            set {
                if ((this.RoadTypeField.Equals(value) != true)) {
                    this.RoadTypeField = value;
                    this.RaisePropertyChanged("RoadType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Toilet {
            get {
                return this.ToiletField;
            }
            set {
                if ((this.ToiletField.Equals(value) != true)) {
                    this.ToiletField = value;
                    this.RaisePropertyChanged("Toilet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Under21 {
            get {
                return this.Under21Field;
            }
            set {
                if ((this.Under21Field.Equals(value) != true)) {
                    this.Under21Field = value;
                    this.RaisePropertyChanged("Under21");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VehicleID {
            get {
                return this.VehicleIDField;
            }
            set {
                if ((object.ReferenceEquals(this.VehicleIDField, value) != true)) {
                    this.VehicleIDField = value;
                    this.RaisePropertyChanged("VehicleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RentalCar.Service.Workflow.MyVehicleService.VehicleTypes VehicleType {
            get {
                return this.VehicleTypeField;
            }
            set {
                if ((this.VehicleTypeField.Equals(value) != true)) {
                    this.VehicleTypeField = value;
                    this.RaisePropertyChanged("VehicleType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoadTypes", Namespace="http://schemas.datacontract.org/2004/07/RentalCar.Core.Enums")]
    public enum RoadTypes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NULL = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OFF_ROAD = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DIRT_ROAD = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NORMAL_ROAD = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehicleTypes", Namespace="http://schemas.datacontract.org/2004/07/RentalCar.Core.Enums")]
    public enum VehicleTypes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NULL = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        V2WBike = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        V4WDCar = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Campervan = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyVehicleService.IVehicleService")]
    public interface IVehicleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehicleService/Test", ReplyAction="http://tempuri.org/IVehicleService/TestResponse")]
        RentalCar.Service.Workflow.MyVehicleService.TestResponse Test(RentalCar.Service.Workflow.MyVehicleService.TestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehicleService/Test", ReplyAction="http://tempuri.org/IVehicleService/TestResponse")]
        System.Threading.Tasks.Task<RentalCar.Service.Workflow.MyVehicleService.TestResponse> TestAsync(RentalCar.Service.Workflow.MyVehicleService.TestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehicleService/GetVehicle", ReplyAction="http://tempuri.org/IVehicleService/GetVehicleResponse")]
        RentalCar.Service.Workflow.MyVehicleService.GetVehicleResponse GetVehicle(RentalCar.Service.Workflow.MyVehicleService.GetVehicleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehicleService/GetVehicle", ReplyAction="http://tempuri.org/IVehicleService/GetVehicleResponse")]
        System.Threading.Tasks.Task<RentalCar.Service.Workflow.MyVehicleService.GetVehicleResponse> GetVehicleAsync(RentalCar.Service.Workflow.MyVehicleService.GetVehicleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehicleService/GetAvailableVehicles", ReplyAction="http://tempuri.org/IVehicleService/GetAvailableVehiclesResponse")]
        RentalCar.Service.Workflow.MyVehicleService.GetAvailableVehiclesResponse GetAvailableVehicles(RentalCar.Service.Workflow.MyVehicleService.GetAvailableVehiclesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehicleService/GetAvailableVehicles", ReplyAction="http://tempuri.org/IVehicleService/GetAvailableVehiclesResponse")]
        System.Threading.Tasks.Task<RentalCar.Service.Workflow.MyVehicleService.GetAvailableVehiclesResponse> GetAvailableVehiclesAsync(RentalCar.Service.Workflow.MyVehicleService.GetAvailableVehiclesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehicleService/Create", ReplyAction="http://tempuri.org/IVehicleService/CreateResponse")]
        RentalCar.Service.Workflow.MyVehicleService.CreateResponse Create(RentalCar.Service.Workflow.MyVehicleService.CreateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehicleService/Create", ReplyAction="http://tempuri.org/IVehicleService/CreateResponse")]
        System.Threading.Tasks.Task<RentalCar.Service.Workflow.MyVehicleService.CreateResponse> CreateAsync(RentalCar.Service.Workflow.MyVehicleService.CreateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Test", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TestRequest {
        
        public TestRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string TestResult;
        
        public TestResponse() {
        }
        
        public TestResponse(string TestResult) {
            this.TestResult = TestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetVehicle", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetVehicleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string numberPlate;
        
        public GetVehicleRequest() {
        }
        
        public GetVehicleRequest(string numberPlate) {
            this.numberPlate = numberPlate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetVehicleResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetVehicleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RentalCar.Service.Workflow.MyVehicleService.VehicleDTO GetVehicleResult;
        
        public GetVehicleResponse() {
        }
        
        public GetVehicleResponse(RentalCar.Service.Workflow.MyVehicleService.VehicleDTO GetVehicleResult) {
            this.GetVehicleResult = GetVehicleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAvailableVehicles", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAvailableVehiclesRequest {
        
        public GetAvailableVehiclesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAvailableVehiclesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAvailableVehiclesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RentalCar.Service.Workflow.MyVehicleService.VehicleDTO[] GetAvailableVehiclesResult;
        
        public GetAvailableVehiclesResponse() {
        }
        
        public GetAvailableVehiclesResponse(RentalCar.Service.Workflow.MyVehicleService.VehicleDTO[] GetAvailableVehiclesResult) {
            this.GetAvailableVehiclesResult = GetAvailableVehiclesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RentalCar.Service.Workflow.MyVehicleService.VehicleDTO vehicle;
        
        public CreateRequest() {
        }
        
        public CreateRequest(RentalCar.Service.Workflow.MyVehicleService.VehicleDTO vehicle) {
            this.vehicle = vehicle;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int CreateResult;
        
        public CreateResponse() {
        }
        
        public CreateResponse(int CreateResult) {
            this.CreateResult = CreateResult;
        }
    }
}
