//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalCar.Client.MySearchVehicleWorkFlow {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MySearchVehicleWorkFlow.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Get", ReplyAction="http://tempuri.org/IService/GetResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="returnVehicle")]
        RentalCar.Core.Models.VehicleDTO Get(string numPlate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Get", ReplyAction="http://tempuri.org/IService/GetResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="returnVehicle")]
        System.Threading.Tasks.Task<RentalCar.Core.Models.VehicleDTO> GetAsync(string numPlate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : RentalCar.Client.MySearchVehicleWorkFlow.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<RentalCar.Client.MySearchVehicleWorkFlow.IService>, RentalCar.Client.MySearchVehicleWorkFlow.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RentalCar.Core.Models.VehicleDTO Get(string numPlate) {
            return base.Channel.Get(numPlate);
        }
        
        public System.Threading.Tasks.Task<RentalCar.Core.Models.VehicleDTO> GetAsync(string numPlate) {
            return base.Channel.GetAsync(numPlate);
        }
    }
}
